package com.hotel.common;

public enum RequestType {
    LOGIN, GET_ROOMS, BOOK_ROOM, REGISTER, ADD_ROOM, DELETE_ROOM, UPDATE_ROOM, GET_HOTELS, GET_CLIENTS, ADD_CLIENT,
    DELETE_CLIENT, UPDATE_CLIENT, GET_BOOKINGS, ADD_BOOKING, DELETE_BOOKING, UPDATE_BOOKING, GET_AMENITIES,
    GET_DASHBOARD, SEARCH_ROOMS, ADD_FAVORITE, REMOVE_FAVORITE, GET_FAVORITES
}